name: Documentation

on:
   push:
      branches: [ RC_1_2 RC_2_0 master ]
   pull_request:

jobs:

   docs:
      name: Docs
      runs-on: ubuntu-20.04

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3

      - name: install dependencies
        run: |
          sudo apt install python-docutils python-pygments python-pil gsfonts inkscape icoutils graphviz hunspell imagemagick
          pip install aafigure
          aafigure --version

      - name: spell-check
        run: |
          cd docs
          make RST2HTML=rst2html spell-check html

      - name: build docs
        run: |
          cd docs
          make RST2HTML=rst2html
