name: Tests (Linux)

on:
   push:
      branches: [ RC_1_2 RC_2_0 master ]
   pull_request:

jobs:

   test:
      name: Tests
      runs-on: ubuntu-20.04

      strategy:
         matrix:
            config: [ crypto=openssl, toolset=clang, deprecated-functions=off ]

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive

      - name: install boost
        run: |
          sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
          echo "using gcc ;" >>~/user-config.jam
          echo "using clang : 9 : clang++-9 ;" >>~/user-config.jam

      - name: build and run tests
        run: |
          cd test
          b2 ${{ matrix.config }} -j2 -l400 debug-iterators=on invariant-checks=full asserts=on picker-debugging=on



   sim:
      name: Simulations
      runs-on: ubuntu-20.04

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive

      - name: install boost
        run: |
          sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
          echo "using gcc ;" >>~/user-config.jam

      - name: build and run simulations
        run: |
          cd simulation
          b2 -j2 debug-iterators=on invariant-checks=full asserts=on picker-debugging=on
