name: Tests (Windows)

on:
   push:
      branches: [ RC_1_2 RC_2_0 master ]
   pull_request:

jobs:

   test:
      name: Tests
      runs-on: windows-latest

      strategy:
         matrix:
            config: [ crypto=openssl, deprecated-functions=off ]

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive

      - name: setup boost
        shell: cmd
        run: |
          set BOOST_ROOT=%BOOST_ROOT_1_72_0%
          cd %BOOST_ROOT%
          bootstrap.bat
          set PATH=%BOOST_ROOT%:%PATH%
          sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
          echo "using msvc ;" >>%HOME%/user-config.jam

      - name: build and run tests
        run: |
          cd test
          b2 ${{ matrix.config }} -j2 -l400 debug-iterators=on invariant-checks=full asserts=on picker-debugging=on



   sim:
      name: Simulations
      runs-on: windows-latest

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive

      - name: setup boost
        shell: cmd
        run: |
          set BOOST_ROOT=%BOOST_ROOT_1_72_0%
          cd %BOOST_ROOT%
          bootstrap.bat
          set PATH=%BOOST_ROOT%:%PATH%
          sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
          echo "using msvc ;" >>%HOME%/user-config.jam

      - name: build and run simulations
        run: |
          cd simulation
          b2 -j2 debug-iterators=on invariant-checks=full asserts=on picker-debugging=on

